name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR private without setting mask-password -> mask credential
        uses: yyichenn/amazon-ecr-login-test@main

      - name: Login to Amazon ECR public without setting mask-password -> mask credential
        uses: yyichenn/amazon-ecr-login-test@main
        with:
          registry-type: public
      
      - name: Login to Amazon ECR private with mask-password = true -> mask credential
        uses: yyichenn/amazon-ecr-login-test@main
        with:
          mask-password: true

      - name: Login to Amazon ECR public with mask-password = true -> mask credential
        uses: yyichenn/amazon-ecr-login-test@main
        with:
          registry-type: public
          mask-password: true
      
      - name: Login to Amazon ECR private with mask-password = false -> NOT mask credential
        uses: yyichenn/amazon-ecr-login-test@main
        with:
          mask-password: false

      - name: Login to Amazon ECR public with mask-password = false -> NOT mask credential
        uses: yyichenn/amazon-ecr-login-test@main
        with:
          registry-type: public
          mask-password: false